### ISSUE TITLE
Can i customize Jetlink chat UI of iOS SDK?

### ISSUE THREAD

**Issue by pimpapare** [jetlinkio/jetlink-ios-sdk#1]

**Comment by kaantezgel** [comment]
Hi,
You can completely customize Jetlink Chat UI with our SDK. JetLinkUIProperties can be used by doing this.
Our Android SDK has this functionality as well. Please, have a check our Android Wiki https://github.com/jetlinkio/jetlink-android-sdk/wiki/How-To-Customize-Chat-Screen

If you need some technical support, please drop a line to hello@jetlink.io

**Comment by pimpapare** [comment]
Thank you :)
