### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by saintjab** [jetlinkio/jetlink-ios-sdk#2]
As a client requirement, I don't use cocoa pods in my project. How can I manually install/add this library to my project?

**Comment by kaantezgel** [comment]
Hi, You can create another empty project, and add JetlinkSDK cocoa pod to that base project. After installing pods you will have a folder whose name is "JetlinkSDK.framework".
Then, you can add this folder to your client's projects and start to use JetlinkSDK.

**Comment by saintjab** [comment]
@kaantezgel , that is working but now am getting a crash even from the example app. 
dyld: Symbol not found: __TMps13IndexableBase
  Referenced from: /private/var/containers/Bundle/Application/1D6494CE-4E27-427A-ACF3-AF8BB211E166/JetlinkSample.app/Frameworks/JetlinkSDK.framework/JetlinkSDK
  Expected in: /private/var/containers/Bundle/Application/1D6494CE-4E27-427A-ACF3-AF8BB211E166/JetlinkSample.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/1D6494CE-4E27-427A-ACF3-AF8BB211E166/JetlinkSample.app/Frameworks/JetlinkSDK.framework/JetlinkSDK
